### ISSUE TITLE
Do we need to run a SQL script to initialize database when setting up the repo? 

### ISSUE THREAD

**Issue by SunnyShikhar** [Janujan/Lyricize#22]
Do I need to run a SQL script to initialize database btw? I was doing a clean install on my work laptop following the steps below:

- I cloned repo
- I created a virtual env `geniusEnv`
- I `pip install -r requirements.txt`
- I run `python3 manage.py runserver`
- Server runs successfully
- Open the home page and type Drake to search
- Hit this error of: `no such table: lyricizer_artist`

![image](https://user-images.githubusercontent.com/11415848/54090978-c1d64300-4350-11e9-8f9a-e0360a3d48d7.png)

**Comment by Janujan** [comment]
yeah you need to make migrations and migrate.

**Comment by SunnyShikhar** [comment]
`python3 manage.py migrate`?

**Comment by Janujan** [comment]
`python manage.py makemigrations`
`python manage.py migrate`

**Comment by SunnyShikhar** [comment]
Oh sheesh, I just did 
`python mange.py migrate` and it worked... didn't do the `makemigrations` so let's see if everything works as is

**Comment by SunnyShikhar** [comment]
What's the `python manage.py makemigrations` for? I just ran it after and response is `No changes detected` so I think I'm good. 

Thanks!

**Comment by Janujan** [comment]
When making changes to database design the workflow is to:
1) make change in the models.py
2) run `python manage.py makemigrations` to build changes for db
3) run `python manage.py migrate` to apply changes

**Comment by Janujan** [comment]
on any fresh install, the initial database still needs to be migrated because the database isn't built. The missing db error isn't caught until you make a call to the database.

**Comment by SunnyShikhar** [comment]
> on any fresh install, the initial database still needs to be migrated because the database isn't built. The missing db error isn't caught until you make a call to the database.

Yup, makes sense, I was hoping it'd be done during the pip install stage with the Django install haha, that's too ideal I suppose. 

> When making changes to database design the workflow is to:

As for^ I was just asking if in the initial install I needa run both commands too just out of curiousity cause at the point I'm not making changes to database design, just need to load the schema

**Comment by Janujan** [comment]
I've always just run both together out of habit. I've had an issue in the past where I tried migrating without running `makemigrations` first and the project got stuck in a weird state that was hard to debug.

**Comment by SunnyShikhar** [comment]
Sicko, I'm fully operational on the work laptop, thanks for the assist 🏀
