### ISSUE TITLE
Album art not being displayed for popular track

### ISSUE THREAD

**Issue by SunnyShikhar** [Janujan/Lyricize#6]
It would be useful to show more context to the track that's pulled by adding the album/song art to it? Thoughts.

**Comment by SunnyShikhar** [comment]
Is this something I'll need to parse on my data side or can you pull the png out in `views.py`? @Janujan

**Comment by SunnyShikhar** [comment]
What do you think about showing album art on the statistics page? @Janujan

**Comment by Janujan** [comment]
Completed this issue by extracting image url from json response and reloading on results page.

**Comment by SunnyShikhar** [comment]
Resolved in #7 @Janujan.
